# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terminalrant < Formula
  desc "Rant space for developers who live in terminal"
  homepage "https://github.com/CrestNiraj12/terminalrant"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/CrestNiraj12/terminalrant/releases/download/v0.2.2/terminalrant_0.2.2_darwin_amd64.tar.gz"
      sha256 "24feef5493cd79126a448699d69e9c7754848c96776a908a88a21df97ba5aec0"

      def install
        bin.install "terminalrant"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/CrestNiraj12/terminalrant/releases/download/v0.2.2/terminalrant_0.2.2_darwin_arm64.tar.gz"
      sha256 "458861bfe67beb2755b67944837d10b4c8c9a80bf16250b92bd5d3f83a78720d"

      def install
        bin.install "terminalrant"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/CrestNiraj12/terminalrant/releases/download/v0.2.2/terminalrant_0.2.2_linux_amd64.tar.gz"
      sha256 "261952ae21917aee0c3f21d178c1355838cb3e7f27fcfafec530679cea691516"
      def install
        bin.install "terminalrant"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/CrestNiraj12/terminalrant/releases/download/v0.2.2/terminalrant_0.2.2_linux_arm64.tar.gz"
      sha256 "b2b709ef8583569db0db703d179daee3a636968364eb245f8ee7215eb285b469"
      def install
        bin.install "terminalrant"
      end
    end
  end

  test do
    system "#{bin}/terminalrant", "--help"
  end
end
