# This file was generated by GoReleaser. DO NOT EDIT.
cask "terminalrant" do
  name "terminalrant"
  desc "Rant space for developers who live in terminal"
  homepage "https://github.com/CrestNiraj12/terminalrant"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terminalrant"

  on_macos do
    on_intel do
      url "https://github.com/CrestNiraj12/terminalrant/releases/download/v#{version}/terminalrant_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/CrestNiraj12/terminalrant/"
      sha256 "efd340a64b7d84155c838e785ff66b195affd00a133da75bccaf1cdae783d56b"
    end
    on_arm do
      url "https://github.com/CrestNiraj12/terminalrant/releases/download/v#{version}/terminalrant_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/CrestNiraj12/terminalrant/"
      sha256 "ece766e7a6198f5c5f072e3a9b4ab31817a188f49ee5d7425680d30e00e9e3ee"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/CrestNiraj12/terminalrant/releases/download/v#{version}/terminalrant_#{version}_linux_amd64.tar.gz",
        verified: "github.com/CrestNiraj12/terminalrant/"
      sha256 "8dd7665bae3cfee0056a9b8c1a3e451607b48aefa0521bf246084e6e5f08e53a"
    end
    on_arm do
      url "https://github.com/CrestNiraj12/terminalrant/releases/download/v#{version}/terminalrant_#{version}_linux_arm64.tar.gz",
        verified: "github.com/CrestNiraj12/terminalrant/"
      sha256 "4d1567c43449c667e92311017c2dfd3d054804d8e75fe037827f942eab173d19"
    end
  end

  # No zap stanza required
end
