# This file was generated by GoReleaser. DO NOT EDIT.
cask "terminalrant" do
  name "terminalrant"
  desc "Rant space for developers who live in terminal"
  homepage "https://github.com/CrestNiraj12/terminalrant"
  version "0.4.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terminalrant"

  on_macos do
    on_intel do
      url "https://github.com/CrestNiraj12/terminalrant/releases/download/v#{version}/terminalrant_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/CrestNiraj12/terminalrant/"
      sha256 "e4ca0444cf21bd319f8dddf1087dd6e1d568c6e9a16d0aef2d93425a2ab29be5"
    end
    on_arm do
      url "https://github.com/CrestNiraj12/terminalrant/releases/download/v#{version}/terminalrant_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/CrestNiraj12/terminalrant/"
      sha256 "f45bbe5b5c473dbfd93eb1212cb25ec74b165904c2e605236f0efdbe1be3e226"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/CrestNiraj12/terminalrant/releases/download/v#{version}/terminalrant_#{version}_linux_amd64.tar.gz",
        verified: "github.com/CrestNiraj12/terminalrant/"
      sha256 "c45d56f0ce7cd686637876b3890464bf173ba34729e541e1be8d1e1439a94360"
    end
    on_arm do
      url "https://github.com/CrestNiraj12/terminalrant/releases/download/v#{version}/terminalrant_#{version}_linux_arm64.tar.gz",
        verified: "github.com/CrestNiraj12/terminalrant/"
      sha256 "ed6a1603e8a4dd878a4ab43c1db3c2f701ff06e96e46ab85ce2239e10e8c501c"
    end
  end

  # No zap stanza required
end
