# This file was generated by GoReleaser. DO NOT EDIT.
cask "terminalrant" do
  name "terminalrant"
  desc "Rant space for developers who live in terminal"
  homepage "https://github.com/CrestNiraj12/terminalrant"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terminalrant"

  on_macos do
    on_intel do
      url "https://github.com/CrestNiraj12/terminalrant/releases/download/v#{version}/terminalrant_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/CrestNiraj12/terminalrant/"
      sha256 "ea2245f68de30600e1cec2ded8c6dc39d09786e41030e9f6a82ef7cf9d9ac326"
    end
    on_arm do
      url "https://github.com/CrestNiraj12/terminalrant/releases/download/v#{version}/terminalrant_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/CrestNiraj12/terminalrant/"
      sha256 "8fc69c9d9e042d8fe6de36ab5edd4e024a4c262d534b1fc494012d447c98a1c3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/CrestNiraj12/terminalrant/releases/download/v#{version}/terminalrant_#{version}_linux_amd64.tar.gz",
        verified: "github.com/CrestNiraj12/terminalrant/"
      sha256 "67b478ec58961224b73a081cc582af24c22c7a4c86f68b5685108f65d6920cdf"
    end
    on_arm do
      url "https://github.com/CrestNiraj12/terminalrant/releases/download/v#{version}/terminalrant_#{version}_linux_arm64.tar.gz",
        verified: "github.com/CrestNiraj12/terminalrant/"
      sha256 "1d529b842bf6c0c61e5a4c0aa4b720e8ffa4d83deb9ca5c4f3b432bc906388f6"
    end
  end

  # No zap stanza required
end
